on:
  push:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          r-version: 4.1.2

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgdown
            animation
            baseballr
            cfbfastR
            chessR
            fastRhockey
            hoopR
            ggimage
            knitr
            ragg
            rsconnect
            sportyR
            tictoc
            toRvik
            wehoop
            zoo
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
