# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    tags: ['*']
  workflow_dispatch:

name: pkgdown

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          r-version: 4.1.2

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgdown
            animation
            baseballr
            cfbfastR
            chessR
            fastRhockey
            ggimage
            hoopR
            knitr
            pacman
            ragg
            rsconnect
            sf
            sportyR
            tictoc
            toRvik
            wehoop
            zoo
          needs: website

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
